<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1048,1083);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1261,1290);
$z[3][4]['name']="position";
$z[4]=Array("channel","\r\n		  <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		  ",1367,1572);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[4][4]['currentstyle']="<li><a href='~typelink~' class='cur' ~rel~>~typename~</a></li>";
$z[5]=Array("field","",1669,1690);
$z[5][4]['name']="content";
$z[6]=Array("include","",1722,1759);
$z[6][4]['filename']="footer.htm";

?>