<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1632,1667);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1820,1849);
$z[3][4]['name']="position";
$z[4]=Array("channel","\r\n		  <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		  ",1923,2128);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[4][4]['currentstyle']="<li><a href='~typelink~' class='cur' ~rel~>~typename~</a></li>";
$z[5]=Array("field","",2264,2283);
$z[5][4]['name']="title";
$z[6]=Array("field","",2332,2384);
$z[6][4]['name']="pubdate";
$z[6][4]['function']="MyDate('Y-m-d',@me)";
$z[7]=Array("field","",2406,2426);
$z[7][4]['name']="source";
$z[8]=Array("field","",2448,2468);
$z[8][4]['name']="writer";
$z[9]=Array("field","",2811,2829);
$z[9][4]['name']="body";
$z[10]=Array("include","",2899,2936);
$z[10][4]['filename']="footer.htm";

?>