
<field:xingming itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xingming>

<field:shouji itemname="手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:shouji>

<field:dizhi itemname="地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dizhi>

<field:neirong itemname="内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:neirong>
