<?php
$z[0]=Array("channelartlist","\r\n		<li> <strong><a href='{dede:field name='typeurl'/}'>{dede:field name='typename' /}</a></strong>\r\n          <div>\r\n		  {dede:channel type='son' noself='yes'}\r\n		  <a href='[field:typelink/]'>[field:typename/]</a>\r\n		  {/dede:channel}\r\n         </div>\r\n        </li>\r\n		",87,423);
$z[0][4]['typeid']="top";
$z[0][4]['row']="7";
$z[1]=Array("global","",967,993);
$z[1][4]['name']="cfg_banquan";
$z[2]=Array("global","",1005,1029);
$z[2][4]['name']="cfg_beian";
$z[3]=Array("flink"," [field:link /] ",1090,1177);
$z[3][4]['row']="24";
$z[3][4]['type']="text";
$z[3][4]['titlelen']="24";
$z[3][4]['typeid']="0";

?>