<?php
$z[0]=Array("field","",257,276);
$z[0][4]['name']="title";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1169,1204);
$z[2][4]['filename']="head.htm";
$z[3]=Array("type","<a href=\"[field:typeurl /]\" target='_blank'>\r\n            <div class=\"info\">\r\n              <h3>[field:typename /]</h3>\r\n              <p></p>\r\n            </div>\r\n            </a>",1844,2058);
$z[3][4]['typeid']="9";
$z[4]=Array("type","<a href=\"[field:typeurl /]\" target='_blank'>\r\n            <div class=\"info\">\r\n              <h3>[field:typename /]</h3>\r\n              <p></p>\r\n            </div>\r\n            </a>",2178,2393);
$z[4][4]['typeid']="10";
$z[5]=Array("type","<a href=\"[field:typeurl /]\">\r\n            <div class=\"info\">\r\n              <h3>[field:typename /]</h3>\r\n              <p></p>\r\n            </div>\r\n            </a>",2513,2712);
$z[5][4]['typeid']="11";
$z[6]=Array("type","<a href=\"[field:typeurl /]\" target='_blank'>\r\n            <div class=\"info\">\r\n              <h3>[field:typename /]</h3>\r\n            </div>\r\n            </a>",2832,3024);
$z[6][4]['typeid']="12";
$z[7]=Array("type","<a href=\"[field:typeurl /]\">\r\n            <div class=\"info\">\r\n              <h3>[field:typename /]</h3>\r\n              <p></p>\r\n            </div>\r\n            </a>",3144,3343);
$z[7][4]['typeid']="13";
$z[8]=Array("include","",5902,5939);
$z[8][4]['filename']="footer.htm";

?>