<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1169,1204);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1400,1429);
$z[3][4]['name']="position";
$z[4]=Array("channel","\r\n		  <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		  ",1506,1711);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[4][4]['currentstyle']="<li><a href='~typelink~' class='cur' ~rel~>~typename~</a></li>";
$z[5]=Array("arclist","\r\n			  <li> <a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:picname/]\" width=\"225\" height=\"155\" /></a> </li>\r\n			  ",1911,2122);
$z[5][4]['typeid']="5";
$z[5][4]['row']="5";
$z[5][4]['titlelen']="20";
$z[5][4]['flag']="p";
$z[5][4]['orderby']="pubdate";
$z[6]=Array("arclist","\r\n				   <li>\r\n                  <h3><a href=\"[field:arcurl/]\" target=\"_blank\">\r\n                	<div class=\"d1_title\"><a href=\"[field:arcurl/]\">[field:title /]</a><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></h3>\r\n                  <p>[field:infos/]...</p>\r\n                  <a href=\"[field:arcurl/]\" target=\"_blank\" class=\"more\">查看详情</a> </li>\r\n				  ",2419,2879);
$z[6][4]['typeid']="5";
$z[6][4]['row']="10";
$z[6][4]['infolen']="200";
$z[6][4]['orderby']="pubdate";
$z[7]=Array("list","\r\n		<li><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title /]</a><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></li>\r\n		",3002,3204);
$z[7][4]['pagesize']="7";
$z[7][4]['titlelen']="80";
$z[7][4]['infolen']="250";
$z[8]=Array("pagelist","",3243,3299);
$z[8][4]['listitem']="pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",3337,3374);
$z[9][4]['filename']="footer.htm";

?>