<?php
$z[0]=Array("field","",257,276);
$z[0][4]['name']="title";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1051,1086);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1256,1285);
$z[3][4]['name']="position";
$z[4]=Array("channel","\r\n		  <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		  ",1359,1564);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[4][4]['currentstyle']="<li><a href='~typelink~' class='cur' ~rel~>~typename~</a></li>";
$z[5]=Array("list","\r\n		<li><img src=\"[field:picname/]\" width=\"240\" height=\"150\" />\r\n          <div class=\"ltt\">[field:title/]</div>\r\n        </li>\r\n		",1672,1853);
$z[5][4]['pagesize']="6";
$z[5][4]['titlelen']="20";
$z[6]=Array("pagelist","",1892,1948);
$z[6][4]['listitem']="pre,next,pageno";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",1986,2023);
$z[7][4]['filename']="footer.htm";

?>