<?php
$z[0]=Array("global","",264,290);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",1159,1194);
$z[1][4]['filename']="head.htm";
$z[2]=Array("field","",1390,1419);
$z[2][4]['name']="position";
$z[3]=Array("list","\r\n		<li><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title /]</a><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></li>\r\n		",1658,1832);
$z[3][4]['perpage']="20";
$z[4]=Array("pagelist","",1871,1927);
$z[4][4]['listitem']="pre,next,pageno";
$z[4][4]['listsize']="5";
$z[5]=Array("include","",1965,2002);
$z[5][4]['filename']="footer.htm";

?>