<?php
$z[0]=Array("field","",257,276);
$z[0][4]['name']="title";
$z[1]=Array("global","",277,303);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1051,1086);
$z[2][4]['filename']="head.htm";
$z[3]=Array("field","",1256,1285);
$z[3][4]['name']="position";
$z[4]=Array("channel","\r\n		  <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		  ",1359,1564);
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['col']="1";
$z[4][4]['currentstyle']="<li><a href='~typelink~' class='cur' ~rel~>~typename~</a></li>";
$z[5]=Array("field","",1660,1681);
$z[5][4]['name']="content";
$z[6]=Array("include","",1713,1750);
$z[6][4]['filename']="footer.htm";

?>