<?php
$z[0]=Array("field","",254,273);
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1048,1083);
$z[2][4]['filename']="head.htm";
$z[3]=Array("type","<a href=\"[field:typeurl /]\"> <img width=\"100\" height=\"90\" src=\"/skin/images/aa1.jpg\" alt=\"\"> <font> [field:typename /]</font></a>",1660,1823);
$z[3][4]['typeid']="9";
$z[4]=Array("type","<a href=\"[field:typeurl /]\"> <img width=\"100\" height=\"90\" src=\"/skin/images/aa2.jpg\" alt=\"\"> <font> [field:typename /]</font></a>",1846,2010);
$z[4][4]['typeid']="10";
$z[5]=Array("type","<a href=\"[field:typeurl /]\"> <img width=\"100\" height=\"90\" src=\"/skin/images/aa3.jpg\" alt=\"\"> <font> [field:typename /]</font></a>",2033,2197);
$z[5][4]['typeid']="11";
$z[6]=Array("type","<a href=\"[field:typeurl /]\"> <img width=\"100\" height=\"90\" src=\"/skin/images/aa4.jpg\" alt=\"\"> <font> [field:typename /]</font></a>",2220,2384);
$z[6][4]['typeid']="12";
$z[7]=Array("type","<a href=\"[field:typeurl /]\"> <img width=\"100\" height=\"90\" src=\"/skin/images/aa5.jpg\" alt=\"\"> <font> [field:typename /]</font></a>",2407,2571);
$z[7][4]['typeid']="13";
$z[8]=Array("field","",2741,2770);
$z[8][4]['name']="position";
$z[9]=Array("channel","\r\n		  <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n		  ",2844,3049);
$z[9][4]['row']="10";
$z[9][4]['type']="son";
$z[9][4]['col']="1";
$z[9][4]['currentstyle']="<li><a href='~typelink~' class='cur' ~rel~>~typename~</a></li>";
$z[10]=Array("field","",3145,3166);
$z[10][4]['name']="content";
$z[11]=Array("include","",3198,3235);
$z[11][4]['filename']="footer.htm";

?>